### ISSUE TITLE
Docker image start error

### ISSUE THREAD

**Issue by 100tomtomas100** [SGFGOV/medusa-strapi-repo#86]
**Describe the bug**
After building an image and starting it I am getting an error
2024-09-29 00:26:53 yarn run v1.22.19
2024-09-29 00:26:53 $ strapi start
2024-09-29 00:27:01 [2024-09-28 21:27:01.661] info: Using Local Image Sharp plugin
2024-09-29 00:27:01 [2024-09-28 21:27:01.669] info: - Source directory: /opt/app/public
2024-09-29 00:27:01 [2024-09-28 21:27:01.677] info: starting strapi in dir /opt/app/config
2024-09-29 00:27:01 [2024-09-28 21:27:01.769] debug: ⛔️ Server wasn't able to start properly.
2024-09-29 00:27:01 [2024-09-28 21:27:01.769] error: Unknown dialect undefined
2024-09-29 00:27:01 Error: Unknown dialect undefined
2024-09-29 00:27:01     at getDialectName (/opt/app/node_modules/@strapi/database/lib/dialects/index.js:36:13)
2024-09-29 00:27:01     at getDialect (/opt/app/node_modules/@strapi/database/lib/dialects/index.js:42:23)
2024-09-29 00:27:01     at new Database (/opt/app/node_modules/@strapi/database/lib/index.js:31:20)
2024-09-29 00:27:01     at Function.Database.init (/opt/app/node_modules/@strapi/database/lib/index.js:121:14)
2024-09-29 00:27:01     at Strapi.bootstrap (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:433:30)
2024-09-29 00:27:01     at Strapi.load (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:504:16)
2024-09-29 00:27:01     at async Strapi.start (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:224:9)
2024-09-29 00:27:01 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-09-29 00:27:01 error Command failed with exit code 1.
**To Reproduce**
After fresh instalation and creation of an image in packages/medusa-strapi with provided Dockerfile.prod
start the image 

**Expected behavior**
Not to get this error

**Comment by 0b1kn00b** [comment]
Here I is doing an activity because no-one is paying any attention

**Comment by SGFGOV** [comment]
i am still using stapi v4 so this isn't a dead repo
